### ISSUE TITLE
App generator "Next steps" instructions outdated

### ISSUE THREAD

**Issue by crandmck** [strongloop/generator-loopback#101]
When creating a new app with `slc loopback`, the instructions it provides at the end are outdated:
```
Next steps:

  Change directory to your app
    $ cd test1

  Create a model in your app
    $ slc loopback:model

  Optional: Enable StrongOps monitoring
    $ slc strongops

  Run the app
    $ slc run .
```
Need to:
- Remove the line about StrongOps, when its deprecated.  Maybe replace with something about Arc?
- Remove the line about using `slc run` because we are deprecating it and not telling people to use it any more.  Should tell them to use `node .` or `slc start`.

**Comment by bajtos** [comment]
> Remove the line about StrongOps, since it is being deprecated. Maybe replace with something about Arc?

@altsang what's your opinion on this?

> Remove the line about using slc run because we are deprecating it and not telling people to use it any more. Should tell them to use node . or slc start.

See #100 and the discussion we have there.

**Comment by altsang** [comment]
@bajtos  - `node .` for details see #100 , thx

**Comment by crandmck** [comment]
@bajtos For the StrongOps part, you can confirm with @chandadharap or @altsang that StrongOps is being deprecated.  Just not sure what text to replace it with, if any.

**Comment by crandmck** [comment]
Per conversation w/Al, replace
```
Run the app
    $ slc run .
```
with
```
Run the app
   $ node .
```
And replace:
```
Optional: Enable StrongOps monitoring
    $ slc strongops
```
with 
```
 Compose your API, run, deploy, profile, and monitor it with Arc:
    $ slc arc
```

**Comment by crandmck** [comment]
This is fixed.
