### ISSUE TITLE
`slc loopback relation` should not offer build-in models for "from"

### ISSUE THREAD

**Issue by transedward** [strongloop/generator-loopback#103]
as mentioned in #35

https://github.com/transedward/loopback-sandbox(the same box I tried reduplicating with my question)

![screen shot 2015-05-14 at 11 07 25 pm](https://cloud.githubusercontent.com/assets/7189930/7634531/133c4236-fa8e-11e4-9c8e-53de1ad6c642.png)

I used `slc loopback:relation` with two built-in models: AccessToken and User as you can see
but After finishing, there is nothing would be shown to proven there are relations between these two models

As you can see, `git status` show there is nothing.

if we use `slc loopback:model` to build a new model then it would show on common/models
then after `slc loopback:relation`, we can see the relation on relation property

what is the best practice of this problem, create every model u gonna use? but then what is built-in for?
or is there some 'magic' after we relation built-in models? then what if we wanna change afterwards? how can we know it's actually effecting?

**Comment by transedward** [comment]
seems like the same problem was discussed on strongloop/loopback#397
hope to see the new solution coming out
but currently, relation still can be defined on generator but can't be seen on json file seems pretty weird and bug-prone.
I don't think it's a good idea.
Probably prohibit this approach and prompt user to do it in built-model.js is better
@bajtos

**Comment by bajtos** [comment]
+1 for modifying the generator to prevent users from creating a relation on a model that cannot be changed (e.g. a built-in model).

**Comment by jannyHou** [comment]
In pr https://github.com/strongloop/generator-loopback/pull/133,
I removed readonly models from choice in `acl`, `property` and 'relation' generators.
Since pr is merged, I am closing it here. thank you!
