### ISSUE TITLE
slc loopback:* is removing remote methods defined on model.json

### ISSUE THREAD

**Issue by lius** [strongloop/generator-loopback#107]
The generator slc loopback:* is erasing the definitions of remote methods present in model's json files (common/models). BTW, the files are reformatted, losing other changes made.

When finished the generator executions (for any parameters, like models, acls, etc), the property "methods" of all files of models has its contents replaced with []. Although this wrong behaviour, the replacement by an array is conceptually wrong IMHO, since https://github.com/strongloop/loopback/commit/019488fe83ffaa7a57df867d367544ea611e9da3 .

**Comment by bajtos** [comment]
Hi @lius, thank you for reporting the issue. I think we need to fix the way how loopback-workspace represents remote methods in model definition. It may be enough to fix the following line:

https://github.com/strongloop/loopback-workspace/blob/a0a9eea8cf617c7a9fd2828c623bc482b4fe40ea/models.json#L179

```diff
- "embed": {"as": "array"},
+ "embed": {"as": "object", "key": "name"},
```

Would you mind contributing the fix yourself?

**Comment by lius** [comment]
Yes. Thanks!
