### ISSUE TITLE
Deprecated dependencies

### ISSUE THREAD

**Issue by rmg** [strongloop/generator-loopback#109]
Currently `npm install` spits out some deprecation warnings related to some nested dependencies. It looks like upgrading to yeoman-generator@0.20.x will clear them up.

```
npm WARN deprecated CSSselect@0.4.1: the module is now available as 'css-select'
npm WARN deprecated CSSwhat@0.4.7: the module is now available as 'css-what'
```

Originally reported in strongloop/strongloop#243

**Comment by rmg** [comment]
Looks like #110 will resolve this if/when it is merged.

**Comment by Amir-61** [comment]
@rmg I'm closing this issue since https://github.com/strongloop/generator-loopback/pull/110 has already been merged... Thanks!
