### ISSUE TITLE
Do not allow relation name to be the same as property name

### ISSUE THREAD

**Issue by crandmck** [strongloop/generator-loopback#118]
The issue https://github.com/strongloop/loopback-datasource-juggler/issues/735 noted that although the generator allows it, a relation name should not be the same as the property name.

The generator should provide an appropriate error message and disallow the choice.

**Comment by jamesobd** [comment]
Why can we not have the relation name and the property name be the same?  It seems to make sense to have an embedded relation like /customer/1234/**products** be tied to a **products** property on customer.
Is there a way to do this that I am missing?

**Comment by jannyHou** [comment]
@jamesobd for example if you create a `hasMany` relation from `Owner` to `Book` called `books`, you can call `owner.books.create( )` to create book instances for a owner instance, if you define a property with the same name, then `owner` instance will be confused.
