### ISSUE TITLE
Implement generator for enabling HTTPS (TLS)

### ISSUE THREAD

**Issue by bajtos** [strongloop/generator-loopback#125]
A public follow-up for the internal discussion in https://github.com/strongloop-internal/scrum-loopback/issues/607.

Implementing a new slc command that can ask the user for location of certificates (or perhaps optionally generate self-signed certs) and make all configuration changes as necessary, so that the app is configured with production-ready TLS & middleware settings.

```
$ slc loopback:enable-https
? Path to key file in PEM format: some/path/key.pem
? Path to certificate file in PEM format: some/path/cert.pem
? Passphrase (optional): 
? Would you like to enable HTTPS for all environments? yes

  Modified server/config.json
  Modified server/middleware.json
```

Security middlewares to consider:
- https://github.com/helmetjs/hsts
- https://github.com/helmetjs/hpkp

**Comment by sam-github** [comment]
Having a generator is a nice convenience for the user, but I suggest that a generator not be used to cover up lack of configurability, it should be possible to drop in a json file with attributes set correctly, or modify an existing json file, and make the app do HTTPS, see https://github.com/strongloop/loopback/issues/2182

**Comment by bajtos** [comment]
generator-loopback has moved to LTS mode, we are not going to add any new features.
