### ISSUE TITLE
Some `slc loopback` commands cannot move through selections

### ISSUE THREAD

**Issue by Amir-61** [strongloop/generator-loopback#131]
Connect to: https://github.com/strongloop/loopback/issues/1731

For some slc loopback commands (e.g. slc loopback:property) the selection does not work with some specific version of Node.

Please see https://github.com/strongloop/loopback/issues/1731

**Comment by Mikk36** [comment]
Still running into this one with 5.8.0 on Windows 10.

`E:\WebStorm\LkrWeb>slc -v`
`strongloop v6.0.0 (node v5.8.0)`
`├── strong-arc@1.8.8 (fb756f2)`
`├── strong-build@2.1.0 (47dd24a)`
`├── strong-deploy@3.1.2 (be6180a)`
`├── strong-mesh-models@8.1.0 (62e539b)`
`├── strong-pm@5.2.0 (4197516)`
`├── strong-registry@1.1.5 (f46e58f)`
`├── strong-start@1.3.2 (1327018)`
`├─┬ strong-supervisor@3.3.1 (1e39220)`
`│ └── strong-agent@2.0.2 (4ea7ee9)`
`├── generator-loopback@1.18.0 (6440776)`
`├── node-inspector@0.7.4`
`└── nodefly-register@0.3.3`

**Comment by Amir-61** [comment]
Duplicate of this [issue](https://github.com/strongloop/generator-loopback/issues/69)

Closing this ticket in favour of this [issue](https://github.com/strongloop/generator-loopback/issues/69)
