### ISSUE TITLE
slc loopback:swagger does not generate valid code from swagger.json if a parameter is a $ref

### ISSUE THREAD

**Issue by MartinLogan** [strongloop/generator-loopback#135]
I have a swagger.json that uses $ref to define a parameter. When I run `slc loopback:swagger` - this generates a method with undefined params .

*Source*
```
...
        "/environments/{envId}": {
            "get": {
                "description": "return the details of an environment",
                "operationId": "getEnvironmentById",
                "produces": [
                    "application/json"
                ],
                "parameters": [
                    {
                        "$ref": "#/parameters/envIdParam"
                    }
                ],

...

    "parameters": {
        "envIdParam": {
            "name": "envId",
            "in": "path",
            "description": "environment ID",
            "required": true,
            "type": "string"
        },

...
```
This produces:

```
/**
 * return the details of an environment
 * @param {any} undefined undefined
 * @callback {Function} callback Callback function
 * @param {Error|string} err Error object
 * @param {errorModel} result Result object
 */
SwaggerApi.getEnvironmentById = function(, callback) {
  // Replace the code below with your implementation.
  // Please make sure the callback is invoked.
  process.nextTick(function() {
    var err = new Error('Not implemented');
    callback(err);
  });
  
}
```

**Comment by richardpringle** [comment]
Hey @MartinLogan, thanks for reporting this issue...but this is actually in the wrong-repo! In other-words, `slc loobpack:swagger` calls another module. 

@jannyHou, this belongs in `loopback-swagger` right?

**Comment by jannyHou** [comment]
@richardpringle True. generator-loopback only take in the parameters to generate a swagger file, but the function called to create it is defined in `loopback-swagger` i believe.

@MartinLogan Could you open the issue in https://github.com/strongloop/loopback-swagger ?

> undefined params 

Sorry I don't quite understand where is the undefined params..for a better debug could you fork https://github.com/strongloop/loopback-sandbox to upload your file, and the code to test your function?
Thanks.

You can mention me after you create a new issue in loopback-swagger. I am glad to help.

**Comment by richardpringle** [comment]
@jannyHou
```node
 @param {any} undefined undefined
```
and
```node
SwaggerApi.getEnvironmentById = function(, callback) {
```
The parameter is missing!

**Comment by MartinLogan** [comment]
np - will do thanks

Martin
