### ISSUE TITLE
Prompt for datasource configuration

### ISSUE THREAD

**Issue by bajtos** [strongloop/generator-loopback#151]
Some connectors (e.g. loopback-connector-cloudant) do not provide any default configuration and require certain settings (e.g. `url`) to be provided by the user. As a result, after a new datasource backed by Cloudant connector was added, the application crashes at startup.

Fortunately, loopback-workspace provides the description of what configuration options are required by each known connector - see [available-connectors.json](https://github.com/strongloop/loopback-workspace/blob/77d240d3d3c2d56d7f903c7de70361651d681a96/available-connectors.json).

We should improve the `datasource` generator to build a series of prompts to correctly configure newly added datasource.

**Comment by cgole** [comment]
Tried this with mysql and it worked. More testing here - https://github.ibm.com/apimesh/scrum-platform-foundation/issues/118

$ apic create --type datasource
? Enter the data-source name: d1
? Select the connector for d1: MySQL (supported by StrongLoop)
Connector-specific configuration:
? host: 166.78.158.45
? port: 3306
? user: test
? password: ************
? database: test
Done running loopback generator

Updating swagger and product definitions
error: Cannot load the LoopBack application: 
WARNING: LoopBack connector "mysql" is not installed as any of the following modules:

 ./connectors/mysql
loopback-connector-mysql

To fix, run:

    npm install loopback-connector-mysql

Cannot load the LoopBack application: 
WARNING: LoopBack connector "mysql" is not installed as any of the following modules:

 ./connectors/mysql
loopback-connector-mysql

To fix, run:

    npm install loopback-connector-mysql

Please fix the problem and run `apic loopback:refresh`

Please fix the problem and run `apic loopback:refresh`
Chandrikas-MacBook-Air:apic1 chandrikagole$ npm install loopback-connector-mysql
npm WARN package.json apic1@1.0.0 No README data
loopback-connector-mysql@2.2.20 node_modules/loopback-connector-mysql
├── async@0.9.2
├── loopback-connector@2.3.15 (async@1.5.2)
├── debug@2.2.0 (ms@0.7.1)
└── mysql@2.10.2 (bignumber.js@2.1.4, readable-stream@1.1.13)
Chandrikas-MacBook-Air:apic1 chandrikagole$ apic loopback:refresh

Updating swagger and product definitions
Created /Users/chandrikagole/workspace/test/apiconnect/apic1/definitions/apic1.yaml swagger description
