### ISSUE TITLE
Tests failing in master

### ISSUE THREAD

**Issue by ritch** [strongloop/generator-loopback#161]
I see several different errors:

```
 1) loopback:export-api-def generator produces JSON format:
     Uncaught Error: Cannot find module 'underscore.string/classify'

 2) loopback:export-api-def generator produces YAML format:
     Uncaught Error: Cannot find module 'underscore.string/classify'
```

...I can no longer reproduce the error, but at some point I was getting a `host` property not defined in `loopback:export-api-def generator `.

@raymondfeng @0candy @bajtos

**Comment by 0candy** [comment]
I have seen this before when the unit test was trying to do `npm install` during dummy project creation but the dependency modules failed to install.

**Comment by bajtos** [comment]
I believe this has been already fixed.
