### ISSUE TITLE
Property default value type is incorrect

### ISSUE THREAD

**Issue by 0candy** [strongloop/generator-loopback#185]
slc loopback
then slc loopback:model
The default value prompt for properties

https://gist.github.com/cfjedimaster/74d0934d4f9f687314c531ab3387fadc
The property is of type "number", but the default value in JSON is of type "string"

Need to fix generator-loopback to convert the default value from string (produced by CLI/yeoman/inquirer prompt) to the correct type. This applies to booleans too, possibly to other types as well.

---

To clarify the scope (see https://github.com/strongloop/generator-loopback/issues/185#issuecomment-225201876 and https://github.com/strongloop/generator-loopback/issues/185#issuecomment-225205571):

 1) When the user creates a model property and provides a default value, then the swagger produced by `apic loopback:refresh` should be valid.

2) The user experience should not be made worser that it is now, this includes users calling the generator via `yo` and `slc` where we don't generate/validate swagger spec.

The current proposal in #200 throws an error when the default value cannot be parsed into property type. Now imagine the case when the user is creating a new model with 10 properties, and the 10th property aborts the generator. That's not acceptable to me.

The coercion of the default value should be implemented in such way, that as little of user input is discarded as possible.

**Comment by bajtos** [comment]
@alexpit to clarify the scope:

 1) When the user creates a model property and provides a default value, then the swagger produced by `apic loopback:refresh` should be valid.

2) The user experience should not be made worser that it is now, this includes users calling the generator via `yo` and `slc` where we don't generate/validate swagger spec.

**Comment by bajtos** [comment]
Elaborating a bit more on the UX part.

The current proposal in #200 throws an error when the default value cannot be parsed into property type. Now imagine the case when the user is creating a new model with 10 properties, and the 10th property aborts the generator. That's not acceptable to me.

The coercion of the default value should be implemented in such way, that as little of user input is discarded as possible.

**Comment by alexpit** [comment]
Fixed in PR #200
