### ISSUE TITLE
Default API name 'swagger_' + basePath. Is it safe to change ?

### ISSUE THREAD

**Issue by aospan** [strongloop/generator-loopback#209]
Hello,

now I'm importing swagger API json file with 'slc loopback:swagger' command and default API model name is 'swagger_' + basePath. I'v found it's hardcoded here generator-loopback/swagger/index.js:

var swaggerModel = 'swagger_' + basePath.replace(/\//g, '_');

Is it safe to change to something else ? For example, for info->title or some user-specified cmd option ?

**Comment by jannyHou** [comment]
@aospan Thank you for the suggestion, could you explain why the `swaggerModel`'s value is important for you? 
From my understanding, it only shows in some log info, like https://github.com/strongloop/generator-loopback/blob/master/swagger/index.js#L253

Does it affect your generated result?
And I think it makes sense to keep the basePath without any custom/user-specified string.
Thought?

**Comment by aospan** [comment]
I mean change 'swagger_' to something more informative. basePath is ok.

**Comment by jannyHou** [comment]
@aospan I believe it's safe if you hack your code to make it more informative. Hmm....on our end I think it's fine to keep it as `swagger_` since it doesn't affect the generated swagger file :)

**Comment by aospan** [comment]
ok, thanks :+1:
