### ISSUE TITLE
Failing test on windows.

### ISSUE THREAD

**Issue by romanso123** [strongloop/generator-loopback#210]
When I "npm test", one of the tests fails on Windows, however on MAC all the tests pass.
Here's a screen shot of the failing test:
![test_error](https://cloud.githubusercontent.com/assets/17109010/16795173/96f4d39a-48e4-11e6-9013-185593b05df7.PNG)

**Comment by bajtos** [comment]
@jannyHou @0candy @richardpringle PTAL. I can see the same problem in @alexpit's https://github.com/strongloop/generator-loopback/pull/200, see http://ci.strongloop.com/job/generator-loopback/1505/

**Comment by richardpringle** [comment]
Looking into it

**Comment by richardpringle** [comment]
@romanso123 
What version of Node and NPM?

**Comment by richardpringle** [comment]
@0candy @jannyHou:

Confirmed, this is a bug. I can reproduce.

**Comment by jannyHou** [comment]
The problem is strong-cached-install only install one dependency module everytime:
https://github.com/strongloop/generator-loopback/blob/master/test/export-api-def.test.js#L44

**Comment by richardpringle** [comment]
@jannyHou, is this only a problem on windows?

@bajtos, I'm throwing a major label on this issue, `npm test` should definitely pass out of the box on every platform.

**Comment by bajtos** [comment]
> The problem is strong-cached-install only install one dependency module everytime:
https://github.com/strongloop/generator-loopback/blob/master/test/export-api-def.test.js#L44

@jannyHou I don't fully understand, let's discuss on Slack.

> @richardpringle I'm throwing a major label on this issue, `npm test` should definitely pass out of the box on every platform.

:+1:

**Comment by bajtos** [comment]
I was able to reproduce this problem in loopback-workspace too, where `npm install` invoked by `strong-cached-install` failed with the following error:

```
Error: Failed to replace env in config: ${APPDATA}
    at C:\Program Files (x86)\nodejs\node_modules\npm\lib\config\core.js:429:13
    at String.replace (native)
    at envReplace (C:\Program Files (x86)\nodejs\node_modules\npm\lib\config\core.js:424:12)
    at parseField (C:\Program Files (x86)\nodejs\node_modules\npm\lib\config\core.js:400:7)
    at C:\Program Files (x86)\nodejs\node_modules\npm\lib\config\core.js:338:17
    at Array.forEach (native)
    at Conf.add (C:\Program Files (x86)\nodejs\node_modules\npm\lib\config\core.js:337:23)
    at ConfigChain.addString (C:\Program Files (x86)\nodejs\node_modules\npm\node_modules\config-chain\index.js:244:8)
    at Conf.<anonymous> (C:\Program Files (x86)\nodejs\node_modules\npm\lib\config\core.js:325:10)
    at C:\Program Files (x86)\nodejs\node_modules\npm\node_modules\graceful-fs\graceful-fs.js:78:16
```

A quick search discovered a related discussion in npm, see https://github.com/npm/npm/issues/7468, which makes me think we have a problem in strong-cached-install - we are too restrictive about which ENV variables are passed to `npm`.

Let's discuss more in https://github.com/strongloop/strong-cached-install/issues/9

**Comment by romanso123** [comment]
@richardpringle 
![npm_node_v](https://cloud.githubusercontent.com/assets/17109010/16899249/c0cf8f1a-4c05-11e6-87a1-897e702f6a57.PNG)

**Comment by jannyHou** [comment]
@bajtos Now all test pass on master branch: http://ci.strongloop.com/job/generator-loopback/1530/

But I am still able to reproduce it on my windows(a crazy unstable system).
I think the error here is different from https://github.com/strongloop/strong-cached-install/issues/9 . 
Let me describe it more detailed: when executing the installation, dependencies should be installed under `test/sandbox/node_modules`, but now when we run the test alone, each time only one dependency goes to `.pkgcache`. And next time we run the test, it installs the previous one in `.pkgcache` to `node_modules`, and adds another new one into `.pkgcache`.

I am reading the code in strong-cached-install. Will update more findings later.
@romanso123 Could you help confirm that you still run into the problem with the latest `generator-loopback`?

**Comment by bajtos** [comment]
See https://github.com/strongloop/strong-cached-install/pull/10, it may fix the problem.

**Comment by richardpringle** [comment]
@jannyHou, feel free to get me to test on windows if it's easier...

**Comment by jannyHou** [comment]
@richardpringle hah Thanks. I have two laptops open now :)

**Comment by jannyHou** [comment]
Confirmed it's fixed again: http://ci.strongloop.com/job/generator-loopback/1559/

Closed.
