### ISSUE TITLE
generator for remote-method not adding method to json file

### ISSUE THREAD

**Issue by 0candy** [strongloop/generator-loopback#222]
Missing additional prompts to generate remote-method

```
/test$ slc loopback:remote-method
? Select the model: model2
? Enter the remote method name: greet
? Is Static? Yes
? Description for method: greeting method

Let's configure where to expose your new method in the public REST API.
You can provide multiple HTTP endpoints, enter an empty path when you are done.
? Enter the path of this endpoint: /greet
? HTTP verb: get
/test$ 
```

Exits after selecting verb and method is not added to JSON file.

**Comment by helenmasters** [comment]
I've seen the same error with apic loopback:remote-method using API Connect v5.0.3.0

The same error is also seen having run `npm install -g yo generator-loopback` and then `yo loopback:remote-method`

**Comment by bajtos** [comment]
I see two issues here:

1) Why does the generator silently abort? If there is some sort of an unhandled error, then the user should be notified about the problem.

2) `loopback:remote-method` does not work, as described above.

**Comment by 0candy** [comment]
PR merged, closing issue.

**Comment by bajtos** [comment]
Released in `generator-loopback@1.24.1`.

> 1) Why does the generator silently abort? If there is some sort of an unhandled error, then the user should be notified about the problem.

@0candy could you PTAL look at this part of the problem too?

**Comment by 0candy** [comment]
@bajtos It silently aborted because one of the generator callback didn't get converted to promises. This is fixed by the PR.

**Comment by bajtos** [comment]
@0candy is there any way how to avoid silent abortion in cases like this one and report an error notifying the user that something went wrong? The thing is, because the generator does not report any error message, users tend to think the method was created for them, and then they don't know how to troubleshoot the problem of a missing remote method.
