### ISSUE TITLE
Generator usage files are not translated.

### ISSUE THREAD

**Issue by 0candy** [strongloop/generator-loopback#227]
Need to move usage files to `intl/en` folder, update code to read help file from that folder and get the translation strings for them.
Name the help file to `.txt`
Put `{{}}` around terms or commands that don't need to be globalized.

**Comment by jannyHou** [comment]
I am afraid the only way to get translation work is **hard-coding all help texts in .txt files and remove usage file in each generator folder.**

Reason:

- Now we rely on `yeoman.base.prototype.help()` to generate the helpString, it's not only returning contents in `Usage` file but also returning other info like usage, options, arguments, etc..., which are generated dynamically. While strong-globalize needs static strings/texts.

- `yeoman.base.prototype.help()` doesn't provide an option to choose a custom path to get usage file. 

We will lose the flexibility to get help infos dynamically which can reflect code change. Eg: If we add a new option to `slc loopback:app`, we need to manually add it in `app.help.txt` to reflect the change then.

I was thinking of overriding function help in yoeman but then I realized as long as those infos are dynamically generated, they are not globalizable...

**Comment by bajtos** [comment]
If this is the approach that apiconnect-loopback-cli is using, then I am ok with that for now.

In the future, if we ever get to refactor our generator to depend less on yeoman, I would prefer to introduce back an auto-generated help file reflecting code changes.

**Comment by jannyHou** [comment]
>  but then I realized as long as those infos are dynamically generated, they are not globalizable...

Realized that It's a wrong assumption. I will override the help() function to generate help String.

**Comment by jannyHou** [comment]
**Verify**

1. Install an old version of `generator-loopback@1.24.4`
2. Run `slc loopback:cmd_name --help` to print old help text. Copy them somewhere for comparison.

  A list of `cmd_name` to be tested:
  - [ ] app
  - [ ] acl
  - [ ] boot-script
  - [ ] datasource
  - [ ] export-api-def
  - [ ] middleware
  - [ ] model
  - [ ] property
  - [ ] relation
  - [ ] remote-method
  - [ ] swagger


3. Uninstall the old one and install `generator-loopback` with the latest commit.
4. Run same commands as step 2 to print new help text.
5. Compare the new version with old version, they should be same.

**Comment by ssh24** [comment]
All the commands above have a missing space, other than that everything looks fine
Example with `swagger`
```
2c2
<   slc loopback:swagger [options] [<url>]
---
>  slc loopback:swagger [options] [<url>]
```

**Comment by jannyHou** [comment]
@ssh24 Nice catch! I will take a look. Thanks!

**Comment by jannyHou** [comment]
@ssh24 missing space is fixed in https://github.com/strongloop/generator-loopback/pull/241
Please verify again. Thanks.

**Comment by ssh24** [comment]
**Verified:**

  A list of `cmd_name` to be tested:
  - [x] app
  - [x] acl
  - [x] boot-script
  - [x] datasource
  - [x] export-api-def
  - [x] middleware
  - [x] model
  - [x] property
  - [x] relation
  - [x] remote-method
  - [x] swagger
