### ISSUE TITLE
Feature Request: Custom Model Location

### ISSUE THREAD

**Issue by greaterweb** [strongloop/generator-loopback#27]
Based on this discussion in the [LoopBack forum](https://groups.google.com/forum/#!topic/loopbackjs/Z-KBT5RBApw), it would be nice to have the option to select the output directory when creating a new model with `yo loopback:model foo`.

It was noted that in the near future there will be options to select the model destination. It would be great to have this look at the `_meta` `sources` values in `model-config.json` and use them.

**Comment by leftclickben** [comment]
:+1: 

When developing a server-only application (e.g. just exposing an API and nothing else) it makes no sense to separate the models out to `common/models`, they should be in `server/models`.

**Comment by bajtos** [comment]
> When developing a server-only application (e.g. just exposing an API and nothing else) it makes no sense to separate the models out to `common/models`, they should be in `server/models`.

For server-only applications, I was thinking about a project layout where all `server/*` files are moved to project's root, i.e.

```
{root}/
 - models/
 - boot/
 - config.json
 - datasources.json
 - middleware.json
 - model-config.json
 - package.json
 (etc.)
```

Thoughts?

**Comment by raymondfeng** [comment]
@leftclickben `server/models` is already supported by LoopBack runtime. Maybe we should add a prompt to `slc loopback:model` to tell if a model is defined for server only.

@bajtos That will probably complicate the tooling quite a bit.

**Comment by bajtos** [comment]
Sure, we can work incrementally, add support for `server/models` now and defer the rest for later.

In the language of loopback-workspace, each project has multiple "facets". Typically there are two facets - "common" and "server".

The solution is to list all project facets in generator-loopback and let the user decide which facet to use. At the moment, the facet name is hard-coded to "common". See [model/index.js#L127](https://github.com/strongloop/generator-loopback/blob/b90e9cdad3979557456982d4de60270b6ced2b77/model/index.js#L127)

**Comment by leftclickben** [comment]
:+1:  

A prompt in the generator to select the facet would be a simple solution.  I'll see if I can put up a PR.

The only other approach I can think of is to set a project-level flag that changes the facet.  That would work for the case where you only want server models, but wouldn't allow some models in `common/models` and some in `server/models`, so I think asking for each model is probably the best approach.

@raymondfeng In my current project, I've just moved the files from `common/models` to `server/models` and deleted `common` -- I'm not adding many models though, it would be a bit painful for a larger / longer project.

@bajtos The problem I can see with moving `server/*` to the project root is that there is other stuff in the project root that shouldn't be a sibling to `server.js` and friends -- things like tests, automation, settings for various tools, the project readme, and so on.  Also artifacts like log files and `node_modules/`.  It's nice to have `server/` to keep the actual application code separate from all these things (especially tests).

**Comment by Amir-61** [comment]
I'm closing this issue as it has already been merged in https://github.com/strongloop/generator-loopback/pull/117/files

Thanks!
