### ISSUE TITLE
CI failure from bluemix related tests

### ISSUE THREAD

**Issue by rashmihunt** [strongloop/generator-loopback#289]
@hacksparrow Current CI fails due to bluemix related tests on master. @raymondfeng tried fixing it through this PR https://github.com/strongloop/generator-loopback/pull/288. But, it still fails with different errors now.  See the CI for this PR - 8 builds are failing. Can you please take a look to fix it?

**Comment by hacksparrow** [comment]
@rashmihunt it's fixed now.
