### ISSUE TITLE
Nsp Security Check Fails

### ISSUE THREAD

**Issue by Lambdac0re** [strongloop/generator-loopback#325]
# Description/Steps to reproduce
Generate a hello-world app

# Expected result
I expect npm test to succeed.
Instead it fails because helmet ^1.3.0 is installed which has a vulnerable dependency.

# Additional information

<pre>
(+) 1 vulnerabilities found                                              
┌───────────────┬───────────────────────────────────────────────────────┐
│               │ Regular Expression Denial of Service                  │
├───────────────┼───────────────────────────────────────────────────────┤
│ Name          │ debug                                                 │
├───────────────┼───────────────────────────────────────────────────────┤
│ CVSS          │ 3.7 (Low)                                             │
├───────────────┼───────────────────────────────────────────────────────┤
│ Installed     │ 2.2.0                                                 │
├───────────────┼───────────────────────────────────────────────────────┤
│ Vulnerable    │ <= 2.6.8 || >= 3.0.0 <= 3.0.1                         │
├───────────────┼───────────────────────────────────────────────────────┤
│ Patched       │ >= 2.6.9 < 3.0.0 || >= 3.1.0                          │
├───────────────┼───────────────────────────────────────────────────────┤
│ Path          │ lbtest1@1.0.0 > helmet@1.3.0 > connect@3.4.1 > debug. │
├───────────────┼───────────────────────────────────────────────────────┤
│ More Info     │ https://nodesecurity.io/advisories/534                │
└───────────────┴───────────────────────────────────────────────────────┘
                                                                         
npm ERR! Test failed.  See above for more details.                       
</pre>

**Comment by dhmlau** [comment]
@Lambdac0re , thanks for reporting this.  I believe this issue has been resolved.
I just ran `nsp check` against this repo, and no known vulnerabilities found.  

Is this issue good to close?  Thanks.

**Comment by dhmlau** [comment]
Hi @Lambdac0re , sorry that I misunderstood your original message.  We're looking into it now.

**Comment by dhmlau** [comment]
@Lambdac0re , it should be fixed in the latest release `5.6.0`.  Could you please try again?  Thanks!

**Comment by Lambdac0re** [comment]
The `nsp check` is successful, but now `npm test` fails the `lint` part with the following message:
```
C:\test1\common\models\message.js
  1:1  error  Use the global form of 'use strict'  strict

? 1 problem (1 error, 0 warnings)
```

**Comment by dhmlau** [comment]
It's a bug.  The workaround is to add the following line at the top of `common\models\message.js`:
```
'use strict';
```
