### ISSUE TITLE
GVT：Hardcode issue in "apic lb"

### ISSUE THREAD

**Issue by candytangnb** [strongloop/generator-loopback#328]
[https://github.ibm.com/velox/toolkit/issues/755](url)

connected to: https://github.com/strongloop-internal/scrum-apex/issues/350

**Comment by candytangnb** [comment]
#https://github.ibm.com/velox/toolkit/issues/758

**Comment by FrankDongNB** [comment]
Hardcode issue in "apic lb"
![image](https://user-images.githubusercontent.com/35794923/35375379-c5ffeb9a-01e1-11e8-9bfd-0723b27b17b0.png)
![image](https://user-images.githubusercontent.com/35794923/35375395-d6e019ee-01e1-11e8-9e2b-5891762006ed.png)

**Comment by dhmlau** [comment]
cross posting my comments from the original github issue:
> Checked with @rfeng,
> - use arrow keys - coming from Yeoman.
> - first screen cap: those are the model names provided by the users
> - the other 3 screen caps: it's debatable whether we need to translate. Please open an issue on generator-loopback. Thanks!

**Comment by dhmlau** [comment]
@raymondfeng @bajtos , do you know where I can find the strings for the first screen cap? Thanks!

**Comment by dhmlau** [comment]
need to look into it.

**Comment by dhmlau** [comment]
The descriptions are coming from the project templates, i.e. the following files:
https://github.com/strongloop/loopback-workspace/blob/master/templates/projects/empty-server/data.js
https://github.com/strongloop/loopback-workspace/blob/master/templates/projects/api-server/data.js
https://github.com/strongloop/loopback-workspace/blob/master/templates/projects/hello-world/data.js
https://github.com/strongloop/loopback-workspace/blob/master/templates/projects/notes/data.js

Running `slt-globalize -e` won't extract the string from those files. 

@jannyHou @bajtos @hacksparrow, do you know how I can get the `template.description` in the template files to be externalized and translated?  Thanks.

**Comment by bajtos** [comment]
I think we need to wrap the string values in `g.f()` call, e.g.

```js
// add at the top
const g = require('strong-globalize')();

// inside the template definition
template.description = g.f('An empty LoopBack API, without any configured ' +
  'models or datasources');
```
