### ISSUE TITLE
Should root display client files by default?

### ISSUE THREAD

**Issue by bdunnette** [strongloop/generator-loopback#33]
The README in the client directory states that it's the location for client HTML, etc.
However, by default, the generated server (specifically, `server/boot/root.js`) displays server status:

```
// Install a `/` route that returns server status
var router = server.loopback.Router();
router.get('/', server.loopback.status());
server.use(router);
```

If the README is correct, shouldn't it have something like `app.use(express.static(__dirname + '/client'));` instead?

**Comment by superkhau** [comment]
@bdunnette This issue is 2 years old, please feel free to submit a modifcation to the README if you have time to contribute. Closing.
