### ISSUE TITLE
GVT：Hardcode issue in "apic lb acl"

### ISSUE THREAD

**Issue by FrankDongNB** [strongloop/generator-loopback#330]
https://github.ibm.com/velox/toolkit/issues/758
Hardcode issue in "apic lb acl"

![image](https://user-images.githubusercontent.com/35794923/35376119-9dde94d8-01e4-11e8-8e58-8cfa5196a0ff.png)
![image](https://user-images.githubusercontent.com/35794923/35376100-8e029104-01e4-11e8-80e2-1a7a0585c487.png)
![image](https://user-images.githubusercontent.com/35794923/35376169-c85d9560-01e4-11e8-9784-e2d99ae009ce.png)
![image](https://user-images.githubusercontent.com/35794923/35376183-d8868f14-01e4-11e8-8144-23b5ceb167a3.png)

connected to: https://github.com/strongloop-internal/scrum-apex/issues/350

**Comment by dhmlau** [comment]
Cross posting my comments in the original issue: 
> Checked with @rfeng,
> - use arrow keys - coming from Yeoman.
> - first screen cap: those are the model names provided by the users
> - the other 3 screen caps: it's debatable whether we need to translate. Please open an issue on generator-loopback. Thanks!

**Comment by dhmlau** [comment]
@raymondfeng @bajtos , do you know where I can find the strings for the last 3 screen caps? Thanks!

**Comment by dhmlau** [comment]
Fixed in this PR: https://github.com/strongloop/loopback-workspace/pull/500
New messages needed to be translated can be found: https://github.com/strongloop/loopback-workspace/blob/master/intl/en/messages.json
