### ISSUE TITLE
`slc loopback:relation` doesn't show built-in models

### ISSUE THREAD

**Issue by clark0x** [strongloop/generator-loopback#35]
Is this intended?

**Comment by transedward** [comment]
Now it will be shown, however seems like it won't be shown in common/models/
how can we know it's really affected or someday we wanna change?
Is any other way to do with that?

**Comment by bajtos** [comment]
> Now it will be shown, however seems like it won't be shown in common/models/

I am afraid I don't understand you. Could you please open a new GH issue for your problem and describe steps to reproduce it? (See the [wiki instructions](https://github.com/strongloop/loopback/wiki/Reporting-issues#bug-report).)

**Comment by transedward** [comment]
thanks for replying, @bajtos already add a new issue

**Comment by transedward** [comment]
seems like the same problem was discussed on strongloop/loopback#397
hope to see the new solution coming out
but currently, relation still can be defined on generator but can't be seen on json file seems pretty weird and bug-prone.
I don't think it's a good idea.
Probably prohibit this approach and prompt user to do it in built-model.js is better
