### ISSUE TITLE
Upgrade yeoman-generator to latest

### ISSUE THREAD

**Issue by bajtos** [strongloop/generator-loopback#355]
~~Prerequisite: a fully working test suite, see #354 (done).~~

Update `yeoman-generator` to the latest version (`^3.0.0` as of now).

Because we are migrating across multiple major versions, we may need to update our code to accommodate breaking changes. Special attention must be paid to model generator that's repeatedly invoking property generator, this scenario must be tested manually via `yo loopback:model`.

**Comment by jannyHou** [comment]
Here is a list of items to do/finished:

- [x] Updated the `acl` generator to extend the latest yeoman generator class
- [x] Updated the tests for `acl` generator to use `yeoman-test`
- [x] Update `loopback-cli` to create the `env` from `yeoman-environment`, see PR https://github.com/strongloop/loopback-cli/pull/71
- [ ] Fix the `help` option
- [ ] Update all generators
  - [ ] app
  - [ ] bluemix
  - [ ] boot-script
  - [ ] datasource
  - [ ] export-api-def
  - [ ] middleware
  - [ ] model
  - [ ] oracle
  - [ ] property
  - [ ] relation
  - [ ] remote-method
  - [ ] soap
  - [ ] swagger
  - [ ] zosconnectee

Related PR: 
- https://github.com/strongloop/loopback-cli/pull/71
- https://github.com/strongloop/generator-loopback/pull/363

**Comment by jannyHou** [comment]
I am closing it since PR https://github.com/strongloop/generator-loopback/pull/363 landed.

Please note there are 2 tests skipped, created a follow up issue to fix them in https://github.com/strongloop/generator-loopback/issues/389
