### ISSUE TITLE
[GSSC-PreTVT]Failed to see cs,pl,ru translation in cs,ru,pl

### ISSUE THREAD

**Issue by candytangnb** [strongloop/generator-loopback#358]
Test case: 11.010.110

Issues:
though cs,pl,ru translation are merged in https://github.com/strongloop/generator-loopback/pull/356 and other prs, the strings are still in English

![image](https://user-images.githubusercontent.com/26452457/42360437-6799ffd2-811b-11e8-8aa7-db95f07f4954.png)

**Comment by virkt25** [comment]
Reason is that we haven't done a new release of the module yet since that PR landed. Should happen today / early next week.

**Comment by candytangnb** [comment]
@virkt25 Sorry but has the new release been available now? If so, I will let Toolkit team to refresh a build.

**Comment by virkt25** [comment]
@candytangnb Yes this particular package was released 2 days ago. Most others have been released but some are pending. Can you please verify and close this issue. Thanks.

**Comment by candytangnb** [comment]
@virkt25 I found that there are still some strings which are in English. 
![image](https://user-images.githubusercontent.com/26452457/42608231-7807f16a-85b9-11e8-9546-5bcc70791f07.png)

@dhmlau I check these still in English strings and cannot find them in the Catch up drop sent out on Jun 11. I check Simplified Chinese and they have been translated. Maybe these strings are not sent out for translation yet. 
![image](https://user-images.githubusercontent.com/26452457/42608243-848dc6bc-85b9-11e8-8b7f-033ddabaf527.png)

**Comment by candytangnb** [comment]
@virkt25 I found that there are still some strings which are in English. 
![image](https://user-images.githubusercontent.com/26452457/42608231-7807f16a-85b9-11e8-9546-5bcc70791f07.png)

@dhmlau I check these still in English strings and cannot find them in the Catch up drop sent out on Jun 11. I check Simplified Chinese and they have been translated. Maybe these strings are not sent out for translation yet. 
![image](https://user-images.githubusercontent.com/26452457/42608243-848dc6bc-85b9-11e8-8b7f-033ddabaf527.png)

**Comment by virkt25** [comment]
Looks like those strings just never got translated

**Comment by candytangnb** [comment]
@dhmlau This test case is included in Catchup TVT begin on Jul 17 & Jul 25. Could these string be ready today? If so, we will add a small drop for them.

**Comment by dhmlau** [comment]
Mentioned to @candytangnb , the *.txt files in https://github.com/strongloop/generator-loopback/blob/master/intl/en/ folder need to be translated.  Thanks.

**Comment by candytangnb** [comment]
@dhmlau do the strings in red line need to be translated? TVT testers open this English strings issue during TVT.
![image](https://user-images.githubusercontent.com/26452457/43059636-fea44646-8e7f-11e8-88ab-5afb57035591.png)

**Comment by candytangnb** [comment]
the same issue in Simplified Chinese
<img width="578" alt="image" src="https://user-images.githubusercontent.com/26452457/43111209-acafd9b0-8f22-11e8-84bd-9019a392472e.png">

**Comment by candytangnb** [comment]
@dhmlau as talking in slack, I summary the issues here
1. 'name' is in English for all 14 languages
2. strings in yellow are in English for 3 catchup languages. Translation have been merged in https://github.com/strongloop/generator-loopback/pull/359

![image](https://user-images.githubusercontent.com/26452457/43112662-b5c4c45a-8f29-11e8-8b13-1e1a481aa2fc.png)

**Comment by dhmlau** [comment]
@candytangnb , thanks for the summary.  Will look into it.

**Comment by candytangnb** [comment]
The original problem in this issue is fixed now.For English string 'name' issues, I open a new issue to track it.https://github.com/strongloop/generator-loopback/issues/377
<img width="1163" alt="image" src="https://user-images.githubusercontent.com/26452457/44183171-8ec22d00-a13c-11e8-82ea-187d0532f921.png">
