### ISSUE TITLE
[GSSC-PreTVT]English string occurs when input lb acl in command line in JPN locale

### ISSUE THREAD

**Issue by gongkegongke** [strongloop/generator-loopback#368]
Test Case: 11.020.060

![image](https://user-images.githubusercontent.com/34856053/44081194-ba2a626c-9fe0-11e8-91fd-6649d40cac00.png)
![image](https://user-images.githubusercontent.com/34856053/44081214-c66eec0a-9fe0-11e8-8fa9-87bb17d84a47.png)

Issue: English string occurs when input **lb acl** in command line

**Comment by dhmlau** [comment]
PR #381

**Comment by dhmlau** [comment]
The mentioned PR will fix the 2 issues:
- `(all existing models)` 
- `other`

**Comment by dhmlau** [comment]
PR #381 is merged. Next is to wait for the translation file to come back from the Aug 21 drop.

**Comment by dhmlau** [comment]
Translation for ja/zh/ko are in.  Released in `generator-loopback@5.9.1`

**Comment by dhmlau** [comment]
All the translation files have been released.  Closing this ticket as resolved.
