### ISSUE TITLE
[GSSC-PreTVT]English string occurs when input lb datasource in command line in JPN locale

### ISSUE THREAD

**Issue by gongkegongke** [strongloop/generator-loopback#370]
Test Case: 11.020.100

![image](https://user-images.githubusercontent.com/34856053/44081620-bc40fdd0-9fe1-11e8-9b2c-eb9389b2151c.png)

Issue: English string occurs when input **lb datasource** in command line

**Comment by dhmlau** [comment]
@jannyHou , do you know where are the highlighted text coming from?  I tried to search in this repo and loopback-cli but couldn't find it.  Thanks.

**Comment by virkt25** [comment]
It comes from `loopback-workspace`, in particular this: https://github.com/strongloop/loopback-workspace/blob/master/available-connectors.json#L10-L20

**Comment by dhmlau** [comment]
@raymondfeng , the text is coming from the json file @virkt25 mentioned. Any idea how we can get it translated?  Thanks.

**Comment by gongkegongke** [comment]
some more English strings are found in this panel, please help to check.

![image](https://user-images.githubusercontent.com/34856053/44333652-00360e80-a4a2-11e8-9447-954f452f6f8d.png)

**Comment by dhmlau** [comment]
@gongkegongke , text above is also coming from available-connectors.json.
https://github.com/strongloop/loopback-workspace/blob/master/available-connectors.json#L598-L615

**Comment by raymondfeng** [comment]
Interesting. I'm not sure if `strong-globalize` scans/translates json files. One possible workaround is to convert it to a `js` file.

**Comment by jannyHou** [comment]
@dhmlau should be fixed by wrapping [this code](https://github.com/strongloop/generator-loopback/blob/master/datasource/index.js#L188) by `g.f()`

**Comment by dhmlau** [comment]
With the [above comment ](https://github.com/strongloop/generator-loopback/issues/370#issuecomment-415030167), I'm closing this ticket as limitation.
