### ISSUE TITLE
[GSSC-PreTVT]English string occurs when input lb export-api-def in command line in JPN locale

### ISSUE THREAD

**Issue by gongkegongke** [strongloop/generator-loopback#371]
Test Case: 11.020.110

![image](https://user-images.githubusercontent.com/34856053/44081780-284c0b00-9fe2-11e8-8e8c-e79345236228.png)

Issue: English string occurs when input **lb export-api-def** in command line

**Comment by dhmlau** [comment]
Most of the text should not be translated because the output is the swagger spec.  However, the `summary` can be translated.  One of `summary` is coming from here: https://github.com/strongloop/loopback/blob/master/lib/model.js#L639

**Comment by dhmlau** [comment]
PR https://github.com/strongloop/loopback/pull/3971

**Comment by dhmlau** [comment]
Translation for ja/zh/ko are in.  Released in `generator-loopback@5.9.1`

**Comment by dhmlau** [comment]
All the translation files have been released.  Closing this ticket as resolved.
