### ISSUE TITLE
[GSSC-PreTVT]English string occurs when input lb middleware in command line in JPN locale

### ISSUE THREAD

**Issue by gongkegongke** [strongloop/generator-loopback#372]
Test Case: 11.020.120

![image](https://user-images.githubusercontent.com/34856053/44081918-845573aa-9fe2-11e8-99f4-216a0feefe7a.png)

Issue: English string occurs when input **lb middleware** in command line

**Comment by raymondfeng** [comment]
No.

**Comment by dhmlau** [comment]
Thanks.
Closing as `working as designed`.
