### ISSUE TITLE
[GSSC-PreTVT]English string occurs when input lb soap in command line in JPN locale

### ISSUE THREAD

**Issue by gongkegongke** [strongloop/generator-loopback#374]
Test Case: 11.020.170

![image](https://user-images.githubusercontent.com/34856053/44082362-90dc0d4a-9fe3-11e8-8605-48c239e50268.png)

Issue: English string occurs when input **lb soap** in command line

**Comment by dhmlau** [comment]
Closing as `working as designed.  Thanks.
