### ISSUE TITLE
[GSSC-PreTVT]English string occurs when input lb swagger in command line in JPN locale

### ISSUE THREAD

**Issue by gongkegongke** [strongloop/generator-loopback#375]
Test Case: 11.020.180

![image](https://user-images.githubusercontent.com/34856053/44082479-ecad6f92-9fe3-11e8-8daa-8fc2625e8ce8.png)

Issue: English string occurs when input **lb swagger** in command line

**Comment by dhmlau** [comment]
I don't think that's something we can fix.
- text in the first 2 highlighted box is coming from Yeoman, one of our our dependencies
- text in last highlighted box is the datasource names and types. They should not be translated.

@raymondfeng @bajtos , could you please confirm?  Thanks.

**Comment by raymondfeng** [comment]
@dhmlau Your assessment is correct.

**Comment by dhmlau** [comment]
Closing as `working as designed`.  Please see the above 2 comments [here](https://github.com/strongloop/generator-loopback/issues/375#issuecomment-413018354) and [here](https://github.com/strongloop/generator-loopback/issues/375#issuecomment-413750516).
