### ISSUE TITLE
[GSSC-TVT]apic lb -h: 'name' is in English

### ISSUE THREAD

**Issue by candytangnb** [strongloop/generator-loopback#377]
Test case: 11.010.110

Issues:
string '' name' is in English.
<img width="1102" alt="image" src="https://user-images.githubusercontent.com/26452457/44183264-db0d6d00-a13c-11e8-977f-0b7f757ca47f.png">

**Comment by dhmlau** [comment]
PR #380 has merged.  Next step is to get the messages.json file translated.

**Comment by dhmlau** [comment]
Paused by translation.  Next translation drop is Aug 21.

**Comment by dhmlau** [comment]
Translation for ja/zh/ko are in.  Released in `generator-loopback@5.9.1`

**Comment by dhmlau** [comment]
All the translation files have been released.  Closing this ticket as resolved.
