### ISSUE TITLE
[GSSC-PreTVT]English string occurs when input lb boot-script in command line in RUS, CHS,FRA locale

### ISSUE THREAD

**Issue by gongkegongke** [strongloop/generator-loopback#382]
Test Case: 11.020.030

![image](https://user-images.githubusercontent.com/34856053/44333797-7175c180-a4a2-11e8-8848-927d59f3335f.png)
![image](https://user-images.githubusercontent.com/34856053/44333818-7b97c000-a4a2-11e8-9c46-d0837ba33230.png)
![image](https://user-images.githubusercontent.com/34856053/44333877-a41fba00-a4a2-11e8-8e43-9fe28da69399.png)

Issue: English string occurs when input boot-script in command line

**Comment by dhmlau** [comment]
@gongkegongke, while the `async` and `sync` words used in the code are translatable, the 2 words  didn't get translated.  

Please see the 2 lines for Chinese: 
https://github.com/strongloop/generator-loopback/blob/master/intl/zh-Hans/messages.json#L17
https://github.com/strongloop/generator-loopback/blob/master/intl/zh-Hans/messages.json#L84

And Russian
https://github.com/strongloop/generator-loopback/blob/master/intl/ru/messages.json#L17
https://github.com/strongloop/generator-loopback/blob/master/intl/ru/messages.json#L84

I suspect it happens in all languages.

**Comment by dhmlau** [comment]
I'm closing this ticket since the code is already doing what it's supposed to.  It is up to the translation team to get it translated if applicable.
