### ISSUE TITLE
[GSSC-TVT]Translator need more Additional information 

### ISSUE THREAD

**Issue by candytangnb** [strongloop/generator-loopback#388]
Test case:11.020.040, 11.020.100

11.020.040 
Please check if following strings are used only for model:

Expose {0} via the REST API?
Let's add some {0} properties now.
Select the datasource to attach {0} to:

In Polish language we need to add descriptor before variable. So those strings cannot be used in many places.
If it is used in many places please create new segments only for model.
![image](https://user-images.githubusercontent.com/26452457/44696614-e3559880-aaaa-11e8-8da6-5db22a9f9046.png)

11.020.100
Same question for 11.020.100:
Select the connector for {0}:
![image](https://user-images.githubusercontent.com/26452457/44696657-097b3880-aaab-11e8-83cc-eb454977fd0d.png)

**Comment by candytangnb** [comment]
@virkt25  Here comes the updates from Polish tester. Please investigate.


Hello,
Please create new segment for "Select the datasource to attach {0} to:" that will be used only in this context, so we could translate it properly.
Regards,
Filip

**Comment by virkt25** [comment]
Not sure I understand what is meant by `create a new segment`.

cc: @dhmlau

**Comment by candytangnb** [comment]
@virkt25 @dhmlau 
Now, only one string in files
 "729c31c15b04f2f5258373531a9a81c3": "Select the datasource to attach {0} to:",

However, for Polish, if this string used in both model and swagger, then the translation for the string will be different.
So polish testers need that something like this
 "729c31c15b04f2f5258373531a9a81c3.**model**": "Select the datasource to attach {0} to:",
 "729c31c15b04f2f5258373531a9a81c3.**swagger**": "Select the datasource to attach {0} to:",

**Comment by dhmlau** [comment]
@candytangnb, I was looking up where the string "Select the datasource to attach" is being used.  I think there is only one instance. 
https://github.com/strongloop/generator-loopback/search?q=%22Select+the+datasource+to+attach%22&unscoped_q=%22Select+the+datasource+to+attach%22

Not sure if I understand the issue correctly,
- for models, `"729c31c15b04f2f5258373531a9a81c3": "Select the datasource to attach {0} to:",` is used
- for swagger, `"92e1c5bd039ab10349417576357dc22e": "Select the datasource to attach models to:"` is used.  
That means we already have separate strings for the 2 cases.

**Comment by candytangnb** [comment]
@dhmlau Thanks so much for the info.

**Comment by dhmlau** [comment]
@candytangnb , with the above info, is this issue good to close? Or there's something outstanding?

**Comment by candytangnb** [comment]
As normally, for tvt issues, we will close issues after confirmation from testers.

**Comment by candytangnb** [comment]
Close per tester's comment
![image](https://user-images.githubusercontent.com/26452457/45678937-151dc480-bb6a-11e8-8ca8-bb1540625a9c.png)
