### ISSUE TITLE
slc loopback:datasource $datasourceName fails silently when run outside of the root dir

### ISSUE THREAD

**Issue by superkhau** [strongloop/generator-loopback#41]
cd $root/server
slc loopback:datasource $datasourceName
Go through the prompts.
Then nothing is added to datasources.json

Should give a warning or something like "Run this command again in the root dir" or detect the root dir automatically.

**Comment by xianlin** [comment]
So far it is still the same behavior if you run "slc loopback:datasource" outside the root dir of loopback project directory.

**Comment by bajtos** [comment]
I believe this has been fixed by #96. Feel free to reopen if the problem persists in the newly scaffolded projects.
