### ISSUE TITLE
Arrow keys not working on Windows

### ISSUE THREAD

**Issue by rmg** [strongloop/generator-loopback#69]
From strongloop/strongloop#182 reported by @ppoliani

> Quite often when I run commands like loopback:relation where you need to select an option, the arrow keys don't work at all. I need to rerun the command multiple time and if i'm lucky i get it work properly.

**Comment by jamesjjk** [comment]
@bajtos Having a problem with arrow keys on our win machines. Running windows 10, latest version of npm 2.13.4, node (io) 2.5, using standard command. Arrow keys work on slc:loopback, slc:model but do not work on relations, acl etc.

**Comment by bajtos** [comment]
@jamesjjk What version of `loopback-generator` do you use? Please upgrade to `v1.11.0` released on Aug 17th and open a new GH issue if the problem is still present. Can you reproduce the bug using different yeoman generators (see http://yeoman.io/generators/)?

**Comment by jamesjjk** [comment]
@bajtos Not having the problem with other yo generators: version

strongloop v5.0.0 (node v2.5.0)
├── strong-arc@1.8.1 (15814c0)
├── strong-build@2.0.4 (9294f54)
├── strong-deploy@3.0.0 (bee617c)
├── strong-mesh-models@8.0.0 (1b220f7)
├── strong-pm@5.0.0 (dbaa1a5)
├── strong-registry@1.1.5 (f46e58f)
├── strong-start@1.3.1 (b17cbc0)
├─┬ strong-supervisor@3.0.2 (539c0ce)
│ └── strong-agent@1.6.4
├── generator-loopback@1.11.0 (dec0654)
├── node-inspector@0.7.4
└── nodefly-register@0.3.3

**Comment by bajtos** [comment]
Thanks @jamesjjk.

I am afraid I don't have a Windows10 machine at the moment, thus I cannot troubleshoot this myself now :(

**Comment by aporlov** [comment]
Quick resolve for Windows 10. Choose "Use legacy console (requires relaunch)" in cmd.exe shortcut properties.

**Comment by jannyHou** [comment]
A workaround: from my experience, git bash(maybe win cmd too) is not working with arrows but node cmd works.

**Comment by imeninnik** [comment]
Well, win 10: my experience shows that arrow does not works if we need to select on the very first prompt (like choose not first model in relations). But on next questions arrows works fine.
So you can create a model with any selections as at first you type the name, and you can create relations for first model in a list, as you select it and then arrow works... Both `slc` and `yo`

**Comment by jeysak** [comment]
works with ConEmu http://www.fosshub.com/ConEmu.html

**Comment by gvillenave** [comment]
Any update on this?

**Comment by eXigentCoder** [comment]
Confirmed working on ConEmu, also couldn't get it to work even in git bash or legacy console

**Comment by jannyHou** [comment]
For windows users, I am afraid a workaround is still this one: https://github.com/strongloop/generator-loopback/issues/69#issuecomment-199859202
@gvillenave

**Comment by YagoLopez** [comment]
f*cking windows. I'm stuck with this stupid issue. Incredibly weird arrow keys work sometimes and sometimes not. Any news or fix for this? I havent installed git bash

**Comment by YagoLopez** [comment]
Here is a temporary solution for Win10. Use this console: http://cmder.net/

**Comment by jamesobd** [comment]
Any permanent solution in the works?
