### ISSUE TITLE
Status middleware triggered for ALL URLs for default scaffolded app 

### ISSUE THREAD

**Issue by crandmck** [strongloop/generator-loopback#80]
When you scaffold an app, by default the status middleware gets triggered not only for the root URL, but for _any_ URL, except for valid API URLs.  So `http://0.0.0.0:3000/`, `http://0.0.0.0:3000/foo`, `http://0.0.0.0:3000/foo/bar/`, and `http://0.0.0.0:3000/foo/bar.html` all trigger the status middleware.

This is a change to the behavior of the default scaffolded app, which used to trigger the status middleware ONLY on the root URL, `http://0.0.0.0:3000/`.   I'm not sure this is really a problem, but it does seem odd that it gets triggered for any invalid URL--you only see the error stack trace when you request an invalid URL that starts with `/api`.  I haven't found any way to actually generate a 404 error (UrlNotFoundError) in the default scaffolded app.

Perhaps this isn't an issue, since it's only with the default scaffolded app, but perhaps it would make more sense to make the status path be `/status` so it's not a "catchall" route.

@raymondfeng suggested I open an issue.

**Comment by crandmck** [comment]
@bajtos PTAL when you have a moment.

**Comment by bajtos** [comment]
@crandmck good catch, the fix is pending review.

**Comment by crandmck** [comment]
Since https://github.com/strongloop/loopback/pull/996 was not merged, perhaps a compromise would be to bind the status middleware to a more specific route, for example `/status`, rather than the root, where it  becomes a "catchall".  Just a thought.

**Comment by crandmck** [comment]
Oh wait, from https://github.com/strongloop/loopback-workspace/pull/182 it looks like you're going to put the status middleware back into `server/boot/root.js`... is that correct?

**Comment by bajtos** [comment]
> Since strongloop/loopback#996 was not merged, perhaps a compromise would be to bind the status middleware to a more specific route, for example /status, rather than the root, where it becomes a "catchall". Just a thought.

This does not solve the problem, the middleware would become "catchall" for URLs starting with "/". Note that the main reason for this whole status URL is to provide a sensible response when opens `http://localhost:3000/` served by a new project. Before we decided to report status, the server was responding with 404.

> Oh wait, from strongloop/loopback-workspace#182 it looks like you're going to put the status middleware back into server/boot/root.js... is that correct?

Yes.

**Comment by bajtos** [comment]
Fixed by https://github.com/strongloop/loopback-workspace/pull/182 and https://github.com/strongloop/generator-loopback/pull/82

@crandmck please verify.

**Comment by crandmck** [comment]
LGTM.  I'm in the process of going through the docs to change them accordingly.

@superkhau Unfortunately, this will require changes to the sample apps (or rather reversion back to the way it was before phases).

**Comment by crandmck** [comment]
Updated docs.  Reassigning to Simon to make changes to samples.  From doc standpoint, the only ones that are critical are loopback-getting-started and loopback-getting-started-intermediate.

**Comment by chandadharap** [comment]
This is simply not scalable. @altsang @raymondfeng @bajtos There are 30+ examples. https://github.com/strongloop/loopback-example

Simon has been doing nothing but updating examples. He will not be able to get to fixing LB bugs at all at this rate.

This needs revisiting. Can we prune and remove some examples. Or mark "deprecated" or "may be out of date" or something? I need Simon to fix LB bugs, and not simply update examples after every such breaking change.

**Comment by crandmck** [comment]
It does seem like a waste of time for Simon....  If I may, I would like to suggest that loopback-getting-started and loopback-getting-started-intermediate be updated (since the tutorials refer to them extensively and rather specifically), and then simply note in https://github.com/strongloop/loopback-example that the other examples don't reflect this particular change.  It's a very specific and uniform change that can be easily described in the README there.  IMO that would be sufficient.

If need be, I could make the changes to loopback-getting-started and loopback-getting-started-intermediate.

**Comment by bajtos** [comment]
The approach we use in `slc loopback:example` is to implement a generator that builds the example via calls to `slc loopback`, `slc loopback:model`, etc. That way it's easy to update the example to the latest version of the scaffolded code by simply re-running the generator again and committing the changes. Then we can implement a tool that will walk through all example repos and execute the update in each of them.

Having said that, there is a limit on how much time we can save by automation. Keeping 30 projects up to date with the latest version of all loopback components will be always time consuming. IMO we should split the examples into two or more "SLA bands" based on how frequently we are updating them and make this distinction clear in the documentation.

**Comment by crandmck** [comment]
Moved to https://github.com/strongloop-internal/scrum-loopback/issues/186.
