### ISSUE TITLE
slc loopback:model doesn't update model-config.json

### ISSUE THREAD

**Issue by Izhaki** [strongloop/generator-loopback#81]
When I run

    slc loopback:model Whatever

My `common` folder seems to be updated alright, but no change to the `model-config.json` file.

Any ideas why?

**Comment by raymondfeng** [comment]
Do you try to create a new model or update an existing one? What changes do you expect to have in model-config.json?

**Comment by Izhaki** [comment]
I'm trying to create a new one. What it doesn't add is this:

    },
        "Statement": {
        "dataSource": "MongoDB",
        "public": true
    },

**Comment by raymondfeng** [comment]
I cannot reproduce it. What version of `slc` do you have? You can find it out by `slc --version`.

What are the steps to reproduce it?

**Comment by Izhaki** [comment]
> strongloop v2.10.1

Another things (which I'm pretty sure off) is that running this command messes up package.json. Is this possible?

I will be able to do some further tests on Tuesday, one thing that could have gone wrong is that fact that I'm running this on a repository that was clone to a different machine and thus I had to run `npm install` - this may have messed up things.

**Comment by bajtos** [comment]
> Another things (which I'm pretty sure of) is that running this command messes up package.json. Is this possible?

Do you have multiple `package.json` files in your project tree (besides node_modules dependencies)? In such case you have run into https://github.com/strongloop/loopback-workspace/issues/181

> Oh, and another thing - I never get to the property definition like most guides say I should. Once the model creating is done, it goes back to command line.

This may be a problem with the yeoman integration. Can you please run `npm install -g generator-loopback` and confirm that the issue can be reproduced via `yo loopback:model Whatever ` too?

**Comment by bajtos** [comment]
We will also need instructions how to reproduce the original problem (`server/model-config.json` not updated) on our machines, otherwise we can't really help you.

**Comment by Izhaki** [comment]
@bajtos Yes - I have package.json on my root and then on `/client`

I guess that's already a great lead for getting things back to work. I'll report results as soon as I have them.

Closing the issue, and will reopen if package.json isn't the issue.

Thanks!
