### ISSUE TITLE
Add generator for boot scripts

### ISSUE THREAD

**Issue by superkhau** [strongloop/generator-loopback#90]
I would like to add a generator to scaffold boot scripts, something like:

```
slc loopback:boot
What kind of boot script would you like to generate?
>o sync
o async
What do you want to name your boot script? <enter name>
[generate <name>.js] in /server/boot with the following contents:
#sync
module.exports = function(app) {
  
}
#async
module.exports = function(app, cb) {
  
  cb();
};
```

@bajtos @raymondfeng @ritch Thoughts?

Connected to #93

**Comment by bajtos** [comment]
Sure, why not. Perhaps `loopback:boot-script` would be a better name.

At the moment, loopback-workspace does not provide any API for boot scripts. I don't think it makes much sense to introduce such API, thus I am proposing to keep the implementation of this feature in the generator only.

**Comment by raymondfeng** [comment]
+1. We should also add 'loopback:method' to generate custom remote method, which is even more useful.

**Comment by superkhau** [comment]
@raymondfeng +1 Remote method is probably even more important. We should probably go with `loopback:remote-method` (sticking with @bajtos `loopback:boot-script` suggestion from above).

We should probably also do `loopback:operation-hook` to make it feature complete.

**Comment by superkhau** [comment]
>+1. We should also add 'loopback:method' to generate custom remote method, which is even more useful.

Track at https://github.com/strongloop/generator-loopback/issues/94

>We should probably also do loopback:operation-hook to make it feature complete.

Track at https://github.com/strongloop/generator-loopback/issues/95

**Comment by superkhau** [comment]
PR at https://github.com/strongloop/generator-loopback/pull/93

**Comment by superkhau** [comment]
@bajtos Removed `yo-rc.json` related code. PTAL again.
